@startuml
'https://plantuml.com/class-diagram

class Algogram
class Usuario

class Feed
class Publicaciones
class Publicacion




Algogram --|> Usuario
Algogram --|> Publicaciones


Usuario --|> Feed



Publicaciones --|> Feed
Publicaciones --|> Publicacion



class Algogram {
    hashmap usuarios
    struct publicaciones
    IniciarSesion(string: usuario)
    bool Deslogear():
}


class Usuario {
    string nombre

    publicar(texto)
    likear(id publicacion, nombre usuario propio)
    ver_feed()
}

class Feed{
    heap publicaciones
    publicaciones_cercanas(nombre usuario)
}

class Publicaciones{
    hashmap publicacion
}

class Publicacion{
    lista personas_dieron_like
    size_t id
    size_t likes
    string texto
    string nombre usuario
}


@enduml